import React from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import './PDFExportButton.css';

const PDFExportButton = ({ results, userName }) => {
  const exportToPDF = async () => {
    const element = document.createElement('div');
    element.style.position = 'absolute';
    element.style.left = '-9999px';
    element.style.padding = '20px';
    element.style.width = '800px';
    element.style.background = 'white';
    element.style.color = 'black';
    
    // Build the PDF content
    element.innerHTML = `
      <div class="pdf-header">
        <h2>Diagnosis Report</h2>
        <div class="doctor-info">
          <p><strong>Doctor:</strong> Dr. ${userName}</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
      <div class="pdf-content">
        ${results.disease ? `
          <div class="pdf-section">
            <h3>Diagnosis</h3>
            <p>${results.disease}</p>
          </div>
        ` : ''}
        ${results.symptoms?.length > 0 ? `
          <div class="pdf-section">
            <h3>Symptoms</h3>
            <ul>
              ${results.symptoms.map(s => `<li>${s}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
        ${results.lab_tests?.length > 0 ? `
          <div class="pdf-section">
            <h3>Lab Tests</h3>
            <ul>
              ${results.lab_tests.map(s => `<li>${s}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
        ${results.medicines?.length > 0 ? `
          <div class="pdf-section">
            <h3>Recommended Medicines</h3>
            <ul>
              ${results.medicines.map(m => `<li>${m}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
        ${results.procedures?.length > 0 ? `
          <div class="pdf-section">
            <h3>Recommended Procedures</h3>
            <ul>
              ${results.procedures.map(p => `<li>${p}</li>`).join('')}
            </ul>
          </div>
        ` : ''}
      </div>
      <div class="pdf-footer">
        <p>Generated by TridoshaRx System</p>
      </div>
    `;
    
    document.body.appendChild(element);
    
    try {
      // Convert to canvas then to PDF
      const canvas = await html2canvas(element);
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`diagnosis-report-${new Date().toISOString().slice(0,10)}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      document.body.removeChild(element);
    }
  };

  return (
    <button className="pdf-export-button" onClick={exportToPDF}>
      Export as PDF
    </button>
  );
};

export default PDFExportButton;

